/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRunTestRouteImport } from './routes/api/run-test'
import { Route as ApiRequirementsRouteImport } from './routes/api/requirements'
import { Route as ApiRejectSuggestedScenarioRouteImport } from './routes/api/reject-suggested-scenario'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAddScenarioRouteImport } from './routes/api/add-scenario'
import { Route as ApiDocsIndexRouteImport } from './routes/api/docs.index'
import { Route as ApiDocsSlugRouteImport } from './routes/api/docs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunTestRoute = ApiRunTestRouteImport.update({
  id: '/api/run-test',
  path: '/api/run-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequirementsRoute = ApiRequirementsRouteImport.update({
  id: '/api/requirements',
  path: '/api/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRejectSuggestedScenarioRoute =
  ApiRejectSuggestedScenarioRouteImport.update({
    id: '/api/reject-suggested-scenario',
    path: '/api/reject-suggested-scenario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddScenarioRoute = ApiAddScenarioRouteImport.update({
  id: '/api/add-scenario',
  path: '/api/add-scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsIndexRoute = ApiDocsIndexRouteImport.update({
  id: '/api/docs/',
  path: '/api/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSlugRoute = ApiDocsSlugRouteImport.update({
  id: '/api/docs/$slug',
  path: '/api/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/add-scenario': typeof ApiAddScenarioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/reject-suggested-scenario': typeof ApiRejectSuggestedScenarioRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/run-test': typeof ApiRunTestRoute
  '/api/docs/$slug': typeof ApiDocsSlugRoute
  '/api/docs': typeof ApiDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/add-scenario': typeof ApiAddScenarioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/reject-suggested-scenario': typeof ApiRejectSuggestedScenarioRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/run-test': typeof ApiRunTestRoute
  '/api/docs/$slug': typeof ApiDocsSlugRoute
  '/api/docs': typeof ApiDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/add-scenario': typeof ApiAddScenarioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/reject-suggested-scenario': typeof ApiRejectSuggestedScenarioRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/run-test': typeof ApiRunTestRoute
  '/api/docs/$slug': typeof ApiDocsSlugRoute
  '/api/docs/': typeof ApiDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/add-scenario'
    | '/api/chat'
    | '/api/events'
    | '/api/reject-suggested-scenario'
    | '/api/requirements'
    | '/api/run-test'
    | '/api/docs/$slug'
    | '/api/docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/add-scenario'
    | '/api/chat'
    | '/api/events'
    | '/api/reject-suggested-scenario'
    | '/api/requirements'
    | '/api/run-test'
    | '/api/docs/$slug'
    | '/api/docs'
  id:
    | '__root__'
    | '/'
    | '/api/add-scenario'
    | '/api/chat'
    | '/api/events'
    | '/api/reject-suggested-scenario'
    | '/api/requirements'
    | '/api/run-test'
    | '/api/docs/$slug'
    | '/api/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAddScenarioRoute: typeof ApiAddScenarioRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiRejectSuggestedScenarioRoute: typeof ApiRejectSuggestedScenarioRoute
  ApiRequirementsRoute: typeof ApiRequirementsRoute
  ApiRunTestRoute: typeof ApiRunTestRoute
  ApiDocsSlugRoute: typeof ApiDocsSlugRoute
  ApiDocsIndexRoute: typeof ApiDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-test': {
      id: '/api/run-test'
      path: '/api/run-test'
      fullPath: '/api/run-test'
      preLoaderRoute: typeof ApiRunTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requirements': {
      id: '/api/requirements'
      path: '/api/requirements'
      fullPath: '/api/requirements'
      preLoaderRoute: typeof ApiRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reject-suggested-scenario': {
      id: '/api/reject-suggested-scenario'
      path: '/api/reject-suggested-scenario'
      fullPath: '/api/reject-suggested-scenario'
      preLoaderRoute: typeof ApiRejectSuggestedScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-scenario': {
      id: '/api/add-scenario'
      path: '/api/add-scenario'
      fullPath: '/api/add-scenario'
      preLoaderRoute: typeof ApiAddScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/': {
      id: '/api/docs/'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/$slug': {
      id: '/api/docs/$slug'
      path: '/api/docs/$slug'
      fullPath: '/api/docs/$slug'
      preLoaderRoute: typeof ApiDocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAddScenarioRoute: ApiAddScenarioRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiRejectSuggestedScenarioRoute: ApiRejectSuggestedScenarioRoute,
  ApiRequirementsRoute: ApiRequirementsRoute,
  ApiRunTestRoute: ApiRunTestRoute,
  ApiDocsSlugRoute: ApiDocsSlugRoute,
  ApiDocsIndexRoute: ApiDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
