/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSyncedDocsRouteImport } from './routes/api/synced-docs'
import { Route as ApiRepositoriesRouteImport } from './routes/api/repositories'
import { Route as ApiPullRouteImport } from './routes/api/pull'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiAllDocsRouteImport } from './routes/api/all-docs'
import { Route as ApiRepositoriesIdRouteImport } from './routes/api/repositories.$id'
import { Route as ApiRepositoriesIdDocsRouteImport } from './routes/api/repositories.$id.docs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncedDocsRoute = ApiSyncedDocsRouteImport.update({
  id: '/api/synced-docs',
  path: '/api/synced-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepositoriesRoute = ApiRepositoriesRouteImport.update({
  id: '/api/repositories',
  path: '/api/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRoute = ApiPullRouteImport.update({
  id: '/api/pull',
  path: '/api/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAllDocsRoute = ApiAllDocsRouteImport.update({
  id: '/api/all-docs',
  path: '/api/all-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepositoriesIdRoute = ApiRepositoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRepositoriesRoute,
} as any)
const ApiRepositoriesIdDocsRoute = ApiRepositoriesIdDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ApiRepositoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/all-docs': typeof ApiAllDocsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pull': typeof ApiPullRoute
  '/api/repositories': typeof ApiRepositoriesRouteWithChildren
  '/api/synced-docs': typeof ApiSyncedDocsRoute
  '/api/repositories/$id': typeof ApiRepositoriesIdRouteWithChildren
  '/api/repositories/$id/docs': typeof ApiRepositoriesIdDocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/all-docs': typeof ApiAllDocsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pull': typeof ApiPullRoute
  '/api/repositories': typeof ApiRepositoriesRouteWithChildren
  '/api/synced-docs': typeof ApiSyncedDocsRoute
  '/api/repositories/$id': typeof ApiRepositoriesIdRouteWithChildren
  '/api/repositories/$id/docs': typeof ApiRepositoriesIdDocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/all-docs': typeof ApiAllDocsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pull': typeof ApiPullRoute
  '/api/repositories': typeof ApiRepositoriesRouteWithChildren
  '/api/synced-docs': typeof ApiSyncedDocsRoute
  '/api/repositories/$id': typeof ApiRepositoriesIdRouteWithChildren
  '/api/repositories/$id/docs': typeof ApiRepositoriesIdDocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/all-docs'
    | '/api/config'
    | '/api/events'
    | '/api/pull'
    | '/api/repositories'
    | '/api/synced-docs'
    | '/api/repositories/$id'
    | '/api/repositories/$id/docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/all-docs'
    | '/api/config'
    | '/api/events'
    | '/api/pull'
    | '/api/repositories'
    | '/api/synced-docs'
    | '/api/repositories/$id'
    | '/api/repositories/$id/docs'
  id:
    | '__root__'
    | '/'
    | '/api/all-docs'
    | '/api/config'
    | '/api/events'
    | '/api/pull'
    | '/api/repositories'
    | '/api/synced-docs'
    | '/api/repositories/$id'
    | '/api/repositories/$id/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAllDocsRoute: typeof ApiAllDocsRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiPullRoute: typeof ApiPullRoute
  ApiRepositoriesRoute: typeof ApiRepositoriesRouteWithChildren
  ApiSyncedDocsRoute: typeof ApiSyncedDocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/synced-docs': {
      id: '/api/synced-docs'
      path: '/api/synced-docs'
      fullPath: '/api/synced-docs'
      preLoaderRoute: typeof ApiSyncedDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repositories': {
      id: '/api/repositories'
      path: '/api/repositories'
      fullPath: '/api/repositories'
      preLoaderRoute: typeof ApiRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull': {
      id: '/api/pull'
      path: '/api/pull'
      fullPath: '/api/pull'
      preLoaderRoute: typeof ApiPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/all-docs': {
      id: '/api/all-docs'
      path: '/api/all-docs'
      fullPath: '/api/all-docs'
      preLoaderRoute: typeof ApiAllDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repositories/$id': {
      id: '/api/repositories/$id'
      path: '/$id'
      fullPath: '/api/repositories/$id'
      preLoaderRoute: typeof ApiRepositoriesIdRouteImport
      parentRoute: typeof ApiRepositoriesRoute
    }
    '/api/repositories/$id/docs': {
      id: '/api/repositories/$id/docs'
      path: '/docs'
      fullPath: '/api/repositories/$id/docs'
      preLoaderRoute: typeof ApiRepositoriesIdDocsRouteImport
      parentRoute: typeof ApiRepositoriesIdRoute
    }
  }
}

interface ApiRepositoriesIdRouteChildren {
  ApiRepositoriesIdDocsRoute: typeof ApiRepositoriesIdDocsRoute
}

const ApiRepositoriesIdRouteChildren: ApiRepositoriesIdRouteChildren = {
  ApiRepositoriesIdDocsRoute: ApiRepositoriesIdDocsRoute,
}

const ApiRepositoriesIdRouteWithChildren =
  ApiRepositoriesIdRoute._addFileChildren(ApiRepositoriesIdRouteChildren)

interface ApiRepositoriesRouteChildren {
  ApiRepositoriesIdRoute: typeof ApiRepositoriesIdRouteWithChildren
}

const ApiRepositoriesRouteChildren: ApiRepositoriesRouteChildren = {
  ApiRepositoriesIdRoute: ApiRepositoriesIdRouteWithChildren,
}

const ApiRepositoriesRouteWithChildren = ApiRepositoriesRoute._addFileChildren(
  ApiRepositoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAllDocsRoute: ApiAllDocsRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiPullRoute: ApiPullRoute,
  ApiRepositoriesRoute: ApiRepositoriesRouteWithChildren,
  ApiSyncedDocsRoute: ApiSyncedDocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
