/**
 * Type declarations for the embedded server module.
 *
 * This module is only available in production builds.
 * The actual implementation is generated by the build script.
 */

/**
 * Extracts the embedded .output folder to a cache directory
 * @returns Path to the extracted server directory
 */
export function extractEmbeddedServer(): Promise<string>;
