/**
 * Build mode detection
 *
 * Detects whether the CLI is running as a production build (compiled binary)
 * or in development mode (via bun link).
 *
 * Uses the IS_PRODUCTION constant from build-constants.ts which is:
 * - false in the committed default file (for dev mode)
 * - true when generated by the build script (for production builds)
 */

import { IS_PRODUCTION } from "./build-constants";

/**
 * Returns true if running as a compiled production binary,
 * false if running in development via bun link.
 */
export function isProductionBuild(): boolean {
  return IS_PRODUCTION === true;
}
